os: osx
language: node_js
node_js: node
python:
  - 3.5
cache:
  pip: true
  directories:
    - node_modules
before_install:
  - pip install awscli
after_success:
  - cd example
  - npm install
  - npm run build
deploy:
  - aws configure set region us-west-2
  - aws s3 sync ./dist s3://transform-css/$TRAVIS_BRANCH --delete
after_deploy:
  - aws configure set preview.cloudfront true
  - aws configure set preview.create-invalidation true
  - aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"$AWS_CLOUDFRONT_ID\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":2,\"Items\":[\"/index.html\",\"/*\"]},\"CallerReference\":\"$(date+%s)\"}}"
