os: osx
language: node_js
node_js: node
python:
  - 3.5
cache:
  - pip
  - npm
before_install:
  - pip install awscli
after_success:
  - cd example
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI26KZTWLPE2D6EBA
  secret_access_key:
    secure: ZW7KR3T0N+qLS9/HsnuBMQjsX+NJPgkyG4RQsUbWvuqM1LlqrGigyhanovNWkAFlGqQVpsqMl8DklnR6zMPOmGVYGEAlMhQNCOdKyzmcLTkgMDtkyLjq4uVfJu37pzueGV7fCaGDxWEkD3z2mvAs6EMEV0Z4bh31qv0+PHajzOSlNA4fW5gSBNMQgDbBk7XjXLpWIplOsmxtYqsC7B7TDtGQMZy+08XHWHNXA9ajVzsquCxbpNG9aF1vnkq6+NJ1cX0jauvJfM+W4mtcMjihVliEv25GmETHRggMrXfAlAtf/+ese5CoChlFu6Baf9sLgr6t9KDSMhDNJtsEqMmD/4PTK6JmQuW9/ClhedAdg5RVT5uyeZbQalXZGfdOM3piL4SdEMdkDlY25ReKz/6cc6xuJZJn50QkgBydgid1NtweMCnPSW2BqR7g4KkPcGtsqUp3CAkKPvxxIDmdUjLsMEyRi5IJ6TCwcF4DzItgdq7GFg1keClzZY2bfmdq1TTBCCtMIY1cJtf7c2NZ231dUI6lUP6YORoG4f/vqXtSR89GJO+dORTPGxO716pTQO35Gb/13B28ToMw8B/WDWG2gmGLlSJqJ8ReZmjS2Rf8W6rwqnKczebVeGS1F2X2xq4+5vODuoJ2pZcUyMZq90LMrIgtrBAxXoFkhWXSrE21ue8=
  bucket: transform-css
after_deploy:
  - aws configure set region us-west-2
  - aws configure set preview.cloudfront true
  - aws configure set preview.create-invalidation true
  - aws s3 sync ./dist s3://transform-css/$TRAVIS_BRANCH --delete
  - aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"$AWS_CLOUDFRONT_ID\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":2,\"Items\":[\"/index.html\",\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

